.

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -25,7 +25,54 @@ jobs:
     steps:
     - name: Test
       run: |
-        echo "Test" && exit 0
+        echo "Test" && exit 1
+    # - name: Checkout
+    #   uses: actions/checkout@v4
+    # - name: Setup .NET
+    #   uses: actions/setup-dotnet@v4
+    #   with:
+    #     dotnet-version: 8.0.x
+    # - name: Run tests
+    #   run: dotnet test --configuration Release -warnaserror --logger:trx --logger:html --results-directory "TestResults"
+    # - name: Aggregate test results
+    #   uses: EnricoMi/publish-unit-test-result-action@v2
+    #   if: always()
+    #   with:
+    #     files: |
+    #       TestResults/*.trx
+    #     comment_mode: off
+    #     check_run: false
+    #     job_summary: true
+    #     json_file: TestResults/testresult.json
+    # - name: Upload test results
+    #   uses: actions/upload-artifact@v4
+    #   if: always()
+    #   with:
+    #     name: test-results
+    #     path: TestResults
+
+  badges:
+    needs: [build, test]
+    if: always()
+    runs-on: ubuntu-latest
+    permissions:
+      checks: write
+    steps:
+      - name: Dump job context
+        env:
+          JOB_CONTEXT: ${{ toJson(needs) }}
+        run: |
+          echo "CTX: $JOB_CONTEXT"
+          echo "RST: ${{ needs.test.result }}"
+          echo "JSN: ${{ toJson(needs) }}"
+    # - name: Badges
+    #   run: |
+    #     echo "1: ${{ needs.dependent-upon-fails.result }}"
+    #     echo "2: ${{ jobs.build.outputs.exit_code }}"
+    #     echo "3: ${{ jobs.test.outputs.exit_code }}"
+    #     echo "4: ${{ jobs.test.outputs }}"
+    #     echo "5: ${{ toJson(jobs.test.outputs) }}"
+    #     echo "Badges" && exit 0
     # - name: Checkout
     #   uses: actions/checkout@v4
     # - name: Setup .NET
