.

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -8,7 +8,7 @@ jobs:
     steps:
     - name: Test
       run: |
-        echo "Build" && exit 0
+        echo "Build" && exit 1
     #- name: Checkout
     #  uses: actions/checkout@v4
     #- name: Setup .NET
@@ -19,11 +19,14 @@ jobs:
     #  run: dotnet build --configuration Release -warnaserror
 
   test:
+    name: Test
     runs-on: ubuntu-latest
     permissions:
       checks: write
     outputs:
-      test_result_json: ${{ steps.test_results.outputs.json }}
+      test_report_json: ${{ steps.test_report.outputs.json }}
+      coverage_report_json: ${{ steps.coverage_report.outputs.json }}
+      versionA: ${{ steps.vars.outputs.version }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -32,24 +35,47 @@ jobs:
         with:
           dotnet-version: 8.0.x
       - name: Run tests
-        run: dotnet test --configuration Release -warnaserror --logger:trx --logger:html --results-directory "TestResults" --filter "ClassName~SyntaxConfigurationTests"
+        run: dotnet test --configuration Release -warnaserror --logger:trx --logger:html --results-directory "testreport" --filter "ClassName~SyntaxConfigurationTests"
       - name: Aggregate test results
+        id: test_report
         uses: EnricoMi/publish-unit-test-result-action@v2
-        id: test_results
         if: always()
         with:
           files: |
-            TestResults/*.trx
+            testreport/*.trx
           comment_mode: off
           check_run: false
           job_summary: true
-          json_file: TestResults/testresult.json
+          json_file: testreport/testresult.json
+      - name: Aggregate code coverage
+        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
+        if: always()
+        with:
+          reports: testreport/coverage.opencover.*.Tests.xml
+          title: "Code Coverage"
+          targetdir: coveragereport
+          reporttypes: MarkdownSummaryGithub;JsonSummary;Badges
+          license: ${{ secrets.REPORTGENERATOR_LICENSE }}
+      - name: Publish coverage
+        id: coverage_report
+        if: always()
+        shell: bash
+        run: |
+          cat coveragereport/SummaryGithub.md | sed -e 's/# Summary - Code Coverage/## Code Coverage/g' >> $GITHUB_STEP_SUMMARY
+          echo "json=$(cat coveragereport/Summary.json | tr --delete '\n' | sed -e 's/[()\`]/Y/g')" >> $GITHUB_OUTPUT
+        
       - name: Upload test results
         uses: actions/upload-artifact@v4
         if: always()
         with:
           name: test-results
-          path: TestResults
+          path: testreport
+      - name: Upload code coverage results
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: coverage-results
+          path: coveragereport
 
   badges:
     needs: [build, test]
@@ -58,10 +84,33 @@ jobs:
     permissions:
       checks: write
     steps:
-      - name: HelloOut
+      - name: HelloOutA
         run: |
-          echo "tests: ${{ fromJson(needs.test.outputs.test_result_json).stats.runs_succ }} passed"
-          echo "tests: ${{ fromJson(needs.test.outputs.test_result_json).stats.runs_fail }} failed"
+          echo "---"
+          echo "bbuild: ${{ needs.build.result }}"
+          echo "---"
+          echo "coverage: ${{ fromJson(needs.test.outputs.coverage_report_json).summary.linecoverage }} lines"
+          echo "coverage: ${{ fromJson(needs.test.outputs.coverage_report_json).summary.branchcoverage }} branches"
+          echo "coverage: ${{ fromJson(needs.test.outputs.coverage_report_json).summary.methodcoverage }} methods"
+          echo "---"
+          echo "tests: ${{ fromJson(needs.test.outputs.test_report_json).stats.runs_succ }} passed"
+          echo "tests: ${{ fromJson(needs.test.outputs.test_report_json).stats.runs_fail }} failed"
+          echo "---"
+          echo "${{ toJson(needs) }}"
+
+    #  - name: HelloOut
+    #    run: |
+    #      echo "tests: ${{ fromJson(needs.test.outputs.test_report_json).stats.runs_succ }} passed"
+    #      echo "tests: ${{ fromJson(needs.test.outputs.test_report_json).stats.runs_fail }} failed"
+    #  - name: HelloOut
+    #    run: |
+    #      echo "tests   : ${{ fromJson(needs.test.outputs.test_report_json).stats.runs_succ }} passed"
+    #      echo "tests   : ${{ fromJson(needs.test.outputs.test_report_json).stats.runs_fail }} failed"
+    #      # echo "build   : ${{ fromJson(needs.build).result }}"
+    #      # echo "build   : ${{ fromJson(needs.build) }}"
+    #      # echo "coverage: ${{ needs.test.outputs.coverage_report_json }}"
+    #      echo "all     : ${{ toJson(needs) }}"
+    #      echo "all     : ${{ fromJson(needs) }}"
     #   - name: Badges
     #     run: |
     #       echo "RST: ${{ needs.test.result }}"
@@ -81,23 +130,23 @@ jobs:
     #   with:
     #     dotnet-version: 8.0.x
     # - name: Run tests
-    #   run: dotnet test --configuration Release -warnaserror --logger:trx --logger:html --results-directory "TestResults"
+    #   run: dotnet test --configuration Release -warnaserror --logger:trx --logger:html --results-directory "testreport"
     # - name: Aggregate test results
     #   uses: EnricoMi/publish-unit-test-result-action@v2
     #   if: always()
     #   with:
     #     files: |
-    #       TestResults/*.trx
+    #       testreport/*.trx
     #     comment_mode: off
     #     check_run: false
     #     job_summary: true
-    #     json_file: TestResults/testresult.json
+    #     json_file: testreport/testresult.json
     # - name: Upload test results
     #   uses: actions/upload-artifact@v4
     #   if: always()
     #   with:
     #     name: test_results
-    #     path: TestResults
+    #     path: testreport
 
   # badges:
   #   needs: [build, test]
@@ -109,14 +158,14 @@ jobs:
   #       echo "Badges" && exit 0
     # steps:
     # - name: Test
-    #   run: dotnet test --configuration Release -warnaserror --logger:trx --logger:html --results-directory "TestResults"
+    #   run: dotnet test --configuration Release -warnaserror --logger:trx --logger:html --results-directory "testreport"
     # - name: Create Test Coverage Badge
     #   uses: simon-k/dotnet-code-coverage-badge@v1.0.0
     #   id: create_coverage_badge
     #   with:
     #     label: Unit Test Coverage
     #     color: brightgreen
-    #     path: TestResults/coverage.opencover.xml
+    #     path: testreport/coverage.opencover.xml
     #     gist-filename: plainquire-code-coverage-badge.json
     #     gist-id: 138006474693c9a3040e469ede06a423
     #     gist-auth-token: ${{ secrets.CODE_COVERAGE_BADGE }}
@@ -125,14 +174,14 @@ jobs:
     #  if: always()
     #  with:
     #    files: |
-    #      TestResults/*.trx
+    #      testreport/*.trx
     #    comment_mode: off
     #    check_run: false
     #    job_summary: true
-    #    json_file: TestResults/testresult.json
+    #    json_file: testreport/testresult.json
     #- name: Upload test results
     #  uses: actions/upload-artifact@v4
     #  if: always()
     #  with:
     #    name: test_results
-    #    path: TestResults
+    #    path: testreport
